### PR TITLE
Use numpy to make data processing waaaaay faster, plus some additional quality of life changes

### PR DESCRIPTION
**Pull request by lejar**
Hey there,

I switched the data processing to use numpy to make the data processing a lot faster. I profiled it using the data set 3162099. Here is the profile information for that data set:

| Python | numpy | time (s) |
| --- | --- | --- |
|cpython|yes|1|
|cpython|no|2915|
|pypy|yes|30|
|pypy|no|257| 

As you can see, switching to numpy makes it super fast, especially when using cpython. Pypy is a bit slower here, because it's using an emulation mode to run numpy.

Additionally, I've made some quality of life improvements to the manip.py script for you. Now you can just give it the data folder on the command line and it will automatically parse out the stamp and image resolution.

Let me know if you need any help understanding the code. I've left some comments, but I know numpy can be pretty hard to read if you're not used to it. :)

### CODE REVIEW

**Comment by Danukeru** [comment]
Compiling the program with LLVM is faster.

**Comment by sfxman** [comment]
Holy shit 3 orders of magnitude, that's quite something

**Comment by lejar** [comment]
@Danukeru You know you might want to actually read what I did instead of just reading the title and closing it with a vague comment<sup>1</sup>. For example I ported the code to work on all version of python, and made it so that you can just do ```python manip.py data_folder/``` instead of having to go into the script and change values manually for each data set.

1. By the way what do you mean with compiling with llvm is faster? Did you rewrite the whole thing in c++, or do you mean compiling with cythonize?

**Comment by Danukeru** [comment]
Did I stutter? 

I compiled Python on LLVM. I did not say Clang.

Did you read what I actually did? If you did, you shouldn't assume that I can't convert this to numpy on my own.

Clearly you don't know numpy as well as you would think since the numba project evades you in this instance.

Compiling on LLVM is faster.

**Comment by lejar** [comment]
@Danukeru Do you have any timings with the data set 3162099 using numba?

**Comment by lejar** [comment]
@Danukeru  I don't have that data set anymore and the link where it used to be has been removed. Could you upload the data again? I'm genuinely interested in seeing if numba would really be that fast.

**Pull request closed without merging**
