### PR TITLE
Rewritten to use numpy for speed

### PR DESCRIPTION
**Pull request by mjasperse**
Hi guys,
Just saw your youtube video on this project - cool work! But I was genuinely surprised by how long you said it took you to process the data! Please consider the suggested changes if you ever run this script again or make scripts like it in the future. Numpy is you friend whenever working with numerical data in python! :smile:

In general, `append()` should never be used inside tight loops because it necessarily requires _frequent_ memory reallocation, and in this instance you know in advance (from the file size) how much data there will be. Numpy will handle all that for you.

Since I don't have your dataset I quickly generated some test rubbish - your script was projected to take 1hr and mine took 3s. YMMV, but maybe this will be of use to you. You could likely achieve even further speed increase by not splitting the data into separate files because that adds filesystem overhead.

Your channel covers some super interesting projects, keep it up!

Cheers!

### CODE REVIEW

**Comment by DrDub** [comment]
Looks good to me. @Danukeru ?

**Comment by Danukeru** [comment]
Please refer to all the other numpy enthusiast pull requests I've closed.

**Comment by mjasperse** [comment]
Ooof, my bad, didn't see your savage response to #7.

**Comment by Danukeru** [comment]
Furthermore your analysis is wrong. The only reason this is slow is because I have overhead of opening and closing a file each time.

If I wanted to properly deal with it similar to how numpy does it by actually writing everything in a native language under the hood:

a dedicated process throuh multiprocessing that opens files and passes references on for their use, and then frees them once used. Implemented using its own channel because thread contention is not to be trifled with on the GIL.

Please learn the append allocation behaviour here:
https://stackoverflow.com/a/49244249
Memory reallocation becomes less frequent over time, and is IO limited, not compute limited.
Our processors don't run like they do in the 90s, and this also varies by OS.

image

**Comment by mjasperse** [comment]
Amazing. If it runs so fast for you, then it's so strange that you say in the video that it took an *hour* to process a _single_ image! Couldn't that be why people looked at your code to see how it could be so _mind-bogglingly slow_? I didn't even know it was _possible_ to be so slow, so I guess I learnt something! File handles must be crazy slow on modern PCs! I'll be sure to tell all my data-science colleagues to avoid them!

But maybe viewers see it can be run way faster with some simple restructuring. Testing shows orders of magnitude improvement! Practically real-time! Geez, so weird that they might want to contribute to what seemed (on the face of it) like a fun open-source project! But nope, we're all dumb assholes. Cool.

**Comment by Danukeru** [comment]
I didn't make the video. I wrote the code.
And yes. You're a dumb asshole.
You make many assumptions without any actual data.

**Pull request closed without merging**
